/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ventanasMenu;

import excepciones.BDException;
import gestores.GestorMenu;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelos.Producto;

/**
 *
 * @author ACER
 */
public class VentanaCatalogo extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaCatalogo
     */
    public VentanaCatalogo() {
        initComponents();
        cargarCatalogoVisual();
    }

    private void cargarCatalogoVisual() {
        try {
            panelContenedor.removeAll();

            GestorMenu gestor = new GestorMenu();
            List<Producto> lista = gestor.listaProductos();

            for (Producto p : lista) {
                JPanel tarjeta = new JPanel();
                tarjeta.setLayout(new BoxLayout(tarjeta, BoxLayout.Y_AXIS));
                tarjeta.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 1));
                tarjeta.setPreferredSize(new Dimension(155, 210));
                tarjeta.setBackground(Color.WHITE);

                JLabel lblImagen = new JLabel();
                lblImagen.setAlignmentX(Component.CENTER_ALIGNMENT);

                if (p.getFotografia() != null) {
                    ImageIcon iconoOriginal = new ImageIcon(p.getFotografia());
                    Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH);
                    lblImagen.setIcon(new ImageIcon(imagenEscalada));
                } else {
                    lblImagen.setText("Sin Fotografía");
                }

                JLabel lblNombre = new JLabel(p.getNombreProducto());
                lblNombre.setFont(lblNombre.getFont().deriveFont(Font.BOLD));
                lblNombre.setHorizontalAlignment(SwingConstants.CENTER);
                lblNombre.setAlignmentX(Component.CENTER_ALIGNMENT);

                JLabel lblPrecio = new JLabel("Q " + p.getPrecioVenta());
                lblPrecio.setAlignmentX(Component.CENTER_ALIGNMENT);
                lblPrecio.setForeground(new Color(0, 153, 0));

                // cración de la tarjeta 
                tarjeta.add(Box.createVerticalStrut(10)); // espacio superior
                tarjeta.add(lblImagen);
                tarjeta.add(Box.createVerticalStrut(10)); // espacio en medio
                tarjeta.add(lblNombre);
                tarjeta.add(Box.createVerticalStrut(5));  // espacio en medio
                tarjeta.add(lblPrecio);

                panelContenedor.add(tarjeta);
            }

            panelContenedor.revalidate();
            panelContenedor.repaint();

        } catch (BDException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar el menú: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelContenedor = new javax.swing.JPanel();
        btnExportarHTML = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Menu");

        jScrollPane1.setViewportView(panelContenedor);

        btnExportarHTML.setText("Exportar a HTML");
        btnExportarHTML.addActionListener(this::btnExportarHTMLActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnExportarHTML)
                .addGap(0, 381, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExportarHTML, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarHTMLActionPerformed
        try {
            JFileChooser explorador = new JFileChooser();
            explorador.setDialogTitle("Guardar Menú como HTML");

            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Página Web HTML (*.html)", "html");
            explorador.setFileFilter(filtro);

            int respuesta = explorador.showSaveDialog(this);

            if (respuesta == JFileChooser.APPROVE_OPTION) {
                File archivoGuardar = explorador.getSelectedFile();

                if (!archivoGuardar.getName().toLowerCase().endsWith(".html")) {
                    archivoGuardar = new File(archivoGuardar.getParentFile(), archivoGuardar.getName() + ".html");
                }

                GestorMenu gestor = new GestorMenu();
                List<Producto> lista = gestor.listaProductos();          
                gestor.exportarCatalogoHTML(archivoGuardar.getAbsolutePath(), lista);
                JOptionPane.showMessageDialog(this, "El menú se ha exportado exitosamente a HTML.\nPuede abrirlo en cualquier navegador de internet.", "Exportación Exitosa", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error de escritura al exportar el menú: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExportarHTMLActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarHTML;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
