/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanasPedidos;

import gestores.GestorCuenta;
import gestores.GestorMenu;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.DetalleCuenta;

/**
 *
 * @author ACER
 */
public class DialogDetalleCuenta extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogDetalleCuenta.class.getName());

    /**
     * Creates new form DialogDetalleCuenta
     */
    public DialogDetalleCuenta(java.awt.Frame parent, boolean modal, String codigoCuenta) {
        super(parent, modal);
        initComponents();
        this.setTitle("Detalle de la cuenta: " + codigoCuenta);
        cargarDetalle(codigoCuenta);
    }
    
    private void cargarDetalle(String codigoCuenta) {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tablaDetalles.getModel();
            modelo.setRowCount(0);
            
            GestorCuenta gestor = new GestorCuenta();
            List<DetalleCuenta> detalles = gestor.obtenerDetalles(codigoCuenta);
            
            GestorMenu gestorMenu = new GestorMenu();
            List<modelos.Producto> menuCompleto = gestorMenu.listaProductos(); 
            
            for (modelos.DetalleCuenta d : detalles) {
                
                // se busca el nombre del producto comparando los códigos
                String nombreDelProducto = ""; 
                
                for (modelos.Producto p : menuCompleto) {
                    if (p.getCodigoProducto().equals(d.getCodigoProducto())) {
                        nombreDelProducto = p.getNombreProducto();
                        break; 
                    }
                }
                modelo.addRow(new Object[]{
                    d.getCodigoProducto(),
                    nombreDelProducto,      
                    d.getCantidad(),
                    d.getSubtotal()
                });
            }
        } catch (excepciones.BDException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar detalles: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código de producto", "Nombre", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tablaDetalles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDetalles;
    // End of variables declaration//GEN-END:variables
}
