/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanasPedidos;

import gestores.GestorCuenta;
import gestores.GestorInsumo;
import gestores.GestorMenu;
import java.util.List;
import javax.swing.JOptionPane;
import modelos.DetalleCuenta;
import modelos.Producto;
import modelos.Receta;

/**
 *
 * @author ACER
 */
public class DialogAñadirProducto extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogAñadirProducto.class.getName());
    private String cuentaDestino;

    /**
     * Creates new form DialogAñadirProducto
     */
    public DialogAñadirProducto(java.awt.Frame parent, boolean modal, String codigoCuenta) {
        super(parent, modal);
        initComponents();
        this.cuentaDestino = codigoCuenta;
        this.setTitle("Añadiendo a: " + codigoCuenta);
        cargarProductos();
    }
    
    private void cargarProductos() {
        try {
            GestorMenu gestor = new GestorMenu();
            List<Producto> menu = gestor.listaProductos(); //[cite: 1]

            cbProductos.removeAllItems();

            for (modelos.Producto p : menu) {
                cbProductos.addItem(p.getCodigoProducto() + " - " + p.getNombreProducto() + " - " + "Q " + p.getPrecioVenta());
            }
        } catch (excepciones.BDException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar el menú: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbProductos = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCantidad.setText("Cantidad");

        lblProducto.setText("Producto");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(lblCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (cbProductos.getSelectedIndex() == -1 || txtCantidad.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Complete todos los campos.");
                return;
            }

            int cantidad = Integer.parseInt(txtCantidad.getText().trim());
            if (cantidad <= 0) {
                return;
            }

            String[] partes = cbProductos.getSelectedItem().toString().split(" - ");
            String codigoProd = partes[0];
            double precio = Double.parseDouble(partes[2].replace("Q", "").trim());

            GestorMenu gestorMenu = new GestorMenu();
            GestorInsumo gestorInsumo = new GestorInsumo();
            List<Receta> receta = gestorMenu.obtenerRecetaProducto(codigoProd);

            for (modelos.Receta ing : receta) {
                double necesario = ing.getCantidad() * cantidad;
                double actual = gestorInsumo.obtenerStockActual(ing.getCodigoInsumo());
                if (actual < necesario) {
                    JOptionPane.showMessageDialog(this,
                            "INVENTARIO INSUFICIENTE\nFalta el insumo: " + ing.getCodigoInsumo(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // guarda y descuenta
            double subtotal = cantidad * precio;
            DetalleCuenta detalle = new DetalleCuenta(cuentaDestino, cantidad, codigoProd, subtotal);

            GestorCuenta gestorCuenta = new GestorCuenta();
            gestorCuenta.agregarDetalle(detalle);

            for (int c = 0; c < cantidad; c++) {
                gestorMenu.descontarInsumoPorVentas(codigoProd);
            }

            JOptionPane.showMessageDialog(this, "Producto añadido con éxito.");
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbProductos;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
