/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanasPincipal;

import gestores.GestorNominas;
import javax.swing.JOptionPane;
import ventanasReportes.*;
import ventanasPedidos.*;
import ventanaMesas.*;
import ventanasMenu.*;
import ventanasInventario.*;
import ventanasNominas.*;
import ventanasGestorPersonal.*;

/**
 *
 * @author ACER
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private VentanaListarPersonal ventanaPersonal = null;
    private VentanaRegistrarEmpleado ventanaRegistrar = null;
    private VentanaEditarEmpleado ventanaEditar = null;
    private VentanaHistorialPagos ventanaHistorialPagos = null;
    private VentanaPagos ventanaPagos = null;
    private VentanaInventario ventanaInventario = null;
    private VentanaReabastecerInventario ventanaReabastecer = null;
    private VentanaCatalogo ventanaCatalogo = null;
    private VentanaAgregarProducto ventanaAgregarProducto = null;
    private VentanaMonitoreoMesas ventanaMonitoreoMesas = null;
    private VentanaNuevoPedido ventanaNuevoPedido = null;
    private VentanaCuentasAbiertas ventanaCuentasAbiertas = null;
    private VentanaHistorialCuentas ventanaHistorialCuentas = null;
    private VentanaFlujoCaja ventanaFlujoCaja = null;
    private VentanaBajoStock ventanaBajoStock = null;
    private VentanaProductosMasVendidos ventanaProdMasVendidos = null;
    private VentanaNuevoInsumo ventanaNuevoInsumo = null;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        try {
            GestorNominas gestor = new GestorNominas();
            String mensajeAlerta = gestor.verificarYGenerarPlanillaAutomatica();

            if (mensajeAlerta != null) {
                JOptionPane.showMessageDialog(this, mensajeAlerta, "Nómina Automática", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println("Aviso interno: Error revisando fechas automáticas: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        personalMenu = new javax.swing.JMenu();
        itemListarPersonal = new javax.swing.JMenuItem();
        itemRegistrarEmpleadoNuevo = new javax.swing.JMenuItem();
        itemEditarEmpleado = new javax.swing.JMenuItem();
        nominaMenu = new javax.swing.JMenu();
        itemHistorialPagos = new javax.swing.JMenuItem();
        itemPagos = new javax.swing.JMenuItem();
        inventarioMenu = new javax.swing.JMenu();
        itemVerInventario = new javax.swing.JMenuItem();
        itemReabastecerInventario = new javax.swing.JMenuItem();
        itemNuevoInsumo = new javax.swing.JMenuItem();
        menuMenu = new javax.swing.JMenu();
        itemCatalogo = new javax.swing.JMenuItem();
        itemAgregarProducto = new javax.swing.JMenuItem();
        mesasMenu = new javax.swing.JMenu();
        itemMonitoreoMesas = new javax.swing.JMenuItem();
        pedidoMenu = new javax.swing.JMenu();
        itemNuevoPedido = new javax.swing.JMenuItem();
        itemCuentasAbiertas = new javax.swing.JMenuItem();
        itemHistorialCuentas = new javax.swing.JMenuItem();
        reportesMenu = new javax.swing.JMenu();
        itemFlujoCaja = new javax.swing.JMenuItem();
        itemBajoStock = new javax.swing.JMenuItem();
        itemProdMasVendidos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cafe");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1215, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );

        personalMenu.setText("Personal");

        itemListarPersonal.setText("Listar Personal");
        itemListarPersonal.addActionListener(this::itemListarPersonalActionPerformed);
        personalMenu.add(itemListarPersonal);

        itemRegistrarEmpleadoNuevo.setText("Registrar Empleado Nuevo");
        itemRegistrarEmpleadoNuevo.addActionListener(this::itemRegistrarEmpleadoNuevoActionPerformed);
        personalMenu.add(itemRegistrarEmpleadoNuevo);

        itemEditarEmpleado.setText("Editar Empleado");
        itemEditarEmpleado.addActionListener(this::itemEditarEmpleadoActionPerformed);
        personalMenu.add(itemEditarEmpleado);

        jMenuBar1.add(personalMenu);

        nominaMenu.setText("Nomina");

        itemHistorialPagos.setText("Historial de Pagos");
        itemHistorialPagos.addActionListener(this::itemHistorialPagosActionPerformed);
        nominaMenu.add(itemHistorialPagos);

        itemPagos.setText("Generar y efectuar pagos");
        itemPagos.addActionListener(this::itemPagosActionPerformed);
        nominaMenu.add(itemPagos);

        jMenuBar1.add(nominaMenu);

        inventarioMenu.setText("Inventario");

        itemVerInventario.setText("Ver inventario");
        itemVerInventario.addActionListener(this::itemVerInventarioActionPerformed);
        inventarioMenu.add(itemVerInventario);

        itemReabastecerInventario.setText("Reabastecer inventario");
        itemReabastecerInventario.addActionListener(this::itemReabastecerInventarioActionPerformed);
        inventarioMenu.add(itemReabastecerInventario);

        itemNuevoInsumo.setText("Nuevo insumo");
        itemNuevoInsumo.addActionListener(this::itemNuevoInsumoActionPerformed);
        inventarioMenu.add(itemNuevoInsumo);

        jMenuBar1.add(inventarioMenu);

        menuMenu.setText("Menú");

        itemCatalogo.setText("Catálogo");
        itemCatalogo.addActionListener(this::itemCatalogoActionPerformed);
        menuMenu.add(itemCatalogo);

        itemAgregarProducto.setText("Agregar Producto");
        itemAgregarProducto.addActionListener(this::itemAgregarProductoActionPerformed);
        menuMenu.add(itemAgregarProducto);

        jMenuBar1.add(menuMenu);

        mesasMenu.setText("Mesas");

        itemMonitoreoMesas.setText("Monitoreo de mesas");
        itemMonitoreoMesas.addActionListener(this::itemMonitoreoMesasActionPerformed);
        mesasMenu.add(itemMonitoreoMesas);

        jMenuBar1.add(mesasMenu);

        pedidoMenu.setText("Pedidos");

        itemNuevoPedido.setText("Nuevo pedido");
        itemNuevoPedido.addActionListener(this::itemNuevoPedidoActionPerformed);
        pedidoMenu.add(itemNuevoPedido);

        itemCuentasAbiertas.setText("Cuentas abiertas");
        itemCuentasAbiertas.addActionListener(this::itemCuentasAbiertasActionPerformed);
        pedidoMenu.add(itemCuentasAbiertas);

        itemHistorialCuentas.setText("Historial de cuentas");
        itemHistorialCuentas.addActionListener(this::itemHistorialCuentasActionPerformed);
        pedidoMenu.add(itemHistorialCuentas);

        jMenuBar1.add(pedidoMenu);

        reportesMenu.setText("Reportes");

        itemFlujoCaja.setText("Flujo de Caja");
        itemFlujoCaja.addActionListener(this::itemFlujoCajaActionPerformed);
        reportesMenu.add(itemFlujoCaja);

        itemBajoStock.setText("Insumos con bajo stock");
        itemBajoStock.addActionListener(this::itemBajoStockActionPerformed);
        reportesMenu.add(itemBajoStock);

        itemProdMasVendidos.setText("Productos más vendidos");
        itemProdMasVendidos.addActionListener(this::itemProdMasVendidosActionPerformed);
        reportesMenu.add(itemProdMasVendidos);

        jMenuBar1.add(reportesMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemListarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarPersonalActionPerformed
        if (ventanaPersonal == null || ventanaPersonal.isClosed()) {
            ventanaPersonal = new VentanaListarPersonal();
            jDesktopPane1.add(ventanaPersonal);
            ventanaPersonal.setVisible(true);
        } else {
            ventanaPersonal.toFront();
        }
    }//GEN-LAST:event_itemListarPersonalActionPerformed

    private void itemRegistrarEmpleadoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarEmpleadoNuevoActionPerformed
        if (ventanaRegistrar == null || ventanaRegistrar.isClosed()) {
            ventanaRegistrar = new VentanaRegistrarEmpleado();
            jDesktopPane1.add(ventanaRegistrar);
            ventanaRegistrar.setVisible(true);
        } else {
            ventanaRegistrar.toFront();
        }
    }//GEN-LAST:event_itemRegistrarEmpleadoNuevoActionPerformed

    private void itemEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarEmpleadoActionPerformed
        if (ventanaEditar == null || ventanaEditar.isClosed()) {
            ventanaEditar = new VentanaEditarEmpleado();
            jDesktopPane1.add(ventanaEditar);
            ventanaEditar.setVisible(true);
        } else {
            ventanaEditar.toFront();
        }
    }//GEN-LAST:event_itemEditarEmpleadoActionPerformed

    private void itemHistorialPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHistorialPagosActionPerformed
        if (ventanaHistorialPagos == null || ventanaHistorialPagos.isClosed()) {
            ventanaHistorialPagos = new VentanaHistorialPagos();
            jDesktopPane1.add(ventanaHistorialPagos);
            ventanaHistorialPagos.setVisible(true);
        } else {
            ventanaHistorialPagos.toFront();
        }
    }//GEN-LAST:event_itemHistorialPagosActionPerformed

    private void itemPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPagosActionPerformed
        if (ventanaPagos == null || ventanaPagos.isClosed()) {
            ventanaPagos = new VentanaPagos();
            jDesktopPane1.add(ventanaPagos);
            ventanaPagos.setVisible(true);
        } else {
            ventanaPagos.toFront();
        }
    }//GEN-LAST:event_itemPagosActionPerformed

    private void itemVerInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerInventarioActionPerformed
        if (ventanaInventario == null || ventanaInventario.isClosed()) {
            ventanaInventario = new VentanaInventario();
            jDesktopPane1.add(ventanaInventario);
            ventanaInventario.setVisible(true);
        } else {
            ventanaInventario.toFront();
        }
    }//GEN-LAST:event_itemVerInventarioActionPerformed

    private void itemReabastecerInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReabastecerInventarioActionPerformed
        if (ventanaReabastecer == null || ventanaReabastecer.isClosed()) {
            ventanaReabastecer = new VentanaReabastecerInventario();
            jDesktopPane1.add(ventanaReabastecer);
            ventanaReabastecer.setVisible(true);
        } else {
            ventanaReabastecer.toFront();
        }
    }//GEN-LAST:event_itemReabastecerInventarioActionPerformed

    private void itemCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCatalogoActionPerformed
        if (ventanaCatalogo == null || ventanaCatalogo.isClosed()) {
            ventanaCatalogo = new VentanaCatalogo();
            jDesktopPane1.add(ventanaCatalogo);
            ventanaCatalogo.setVisible(true);
        } else {
            ventanaCatalogo.toFront();
        }
    }//GEN-LAST:event_itemCatalogoActionPerformed

    private void itemAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarProductoActionPerformed
        if (ventanaAgregarProducto == null || ventanaAgregarProducto.isClosed()) {
            ventanaAgregarProducto = new VentanaAgregarProducto();
            jDesktopPane1.add(ventanaAgregarProducto);
            ventanaAgregarProducto.setVisible(true);
        } else {
            ventanaAgregarProducto.toFront();
        }
    }//GEN-LAST:event_itemAgregarProductoActionPerformed

    private void itemMonitoreoMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMonitoreoMesasActionPerformed
        if (ventanaMonitoreoMesas == null || ventanaMonitoreoMesas.isClosed()) {
            ventanaMonitoreoMesas = new VentanaMonitoreoMesas();
            jDesktopPane1.add(ventanaMonitoreoMesas);
            ventanaMonitoreoMesas.setVisible(true);
        } else {
            ventanaMonitoreoMesas.toFront();
        }
    }//GEN-LAST:event_itemMonitoreoMesasActionPerformed

    private void itemNuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoPedidoActionPerformed
        if (ventanaNuevoPedido == null || ventanaNuevoPedido.isClosed()) {
            ventanaNuevoPedido = new VentanaNuevoPedido();
            jDesktopPane1.add(ventanaNuevoPedido);
            ventanaNuevoPedido.setVisible(true);
        } else {
            ventanaNuevoPedido.toFront();
        }
    }//GEN-LAST:event_itemNuevoPedidoActionPerformed

    private void itemCuentasAbiertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCuentasAbiertasActionPerformed
        if (ventanaCuentasAbiertas == null || ventanaCuentasAbiertas.isClosed()) {
            ventanaCuentasAbiertas = new VentanaCuentasAbiertas();
            jDesktopPane1.add(ventanaCuentasAbiertas);
            ventanaCuentasAbiertas.setVisible(true);
        } else {
            ventanaCuentasAbiertas.toFront();
        }
    }//GEN-LAST:event_itemCuentasAbiertasActionPerformed

    private void itemHistorialCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHistorialCuentasActionPerformed
        if (ventanaHistorialCuentas == null || ventanaHistorialCuentas.isClosed()) {
            ventanaHistorialCuentas = new VentanaHistorialCuentas();
            jDesktopPane1.add(ventanaHistorialCuentas);
            ventanaHistorialCuentas.setVisible(true);
        } else {
            ventanaHistorialCuentas.toFront();
        }
    }//GEN-LAST:event_itemHistorialCuentasActionPerformed

    private void itemFlujoCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFlujoCajaActionPerformed
        if (ventanaFlujoCaja == null || ventanaFlujoCaja.isClosed()) {
            ventanaFlujoCaja = new VentanaFlujoCaja();
            jDesktopPane1.add(ventanaFlujoCaja);
            ventanaFlujoCaja.setVisible(true);
        } else {
            ventanaFlujoCaja.toFront();
        }
    }//GEN-LAST:event_itemFlujoCajaActionPerformed

    private void itemBajoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBajoStockActionPerformed
        if (ventanaBajoStock == null || ventanaBajoStock.isClosed()) {
            ventanaBajoStock = new VentanaBajoStock();
            jDesktopPane1.add(ventanaBajoStock);
            ventanaBajoStock.setVisible(true);
        } else {
            ventanaBajoStock.toFront();
        }
    }//GEN-LAST:event_itemBajoStockActionPerformed

    private void itemProdMasVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProdMasVendidosActionPerformed
        if (ventanaProdMasVendidos == null || ventanaProdMasVendidos.isClosed()) {
            ventanaProdMasVendidos = new VentanaProductosMasVendidos();
            jDesktopPane1.add(ventanaProdMasVendidos);
            ventanaProdMasVendidos.setVisible(true);
        } else {
            ventanaProdMasVendidos.toFront();
        }
    }//GEN-LAST:event_itemProdMasVendidosActionPerformed

    private void itemNuevoInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoInsumoActionPerformed
        if (ventanaNuevoInsumo == null || ventanaNuevoInsumo.isClosed()) {
            ventanaNuevoInsumo = new VentanaNuevoInsumo();
            jDesktopPane1.add(ventanaNuevoInsumo);
            ventanaNuevoInsumo.setVisible(true);
        } else {
            ventanaNuevoInsumo.toFront();
        }
    }//GEN-LAST:event_itemNuevoInsumoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu inventarioMenu;
    private javax.swing.JMenuItem itemAgregarProducto;
    private javax.swing.JMenuItem itemBajoStock;
    private javax.swing.JMenuItem itemCatalogo;
    private javax.swing.JMenuItem itemCuentasAbiertas;
    private javax.swing.JMenuItem itemEditarEmpleado;
    private javax.swing.JMenuItem itemFlujoCaja;
    private javax.swing.JMenuItem itemHistorialCuentas;
    private javax.swing.JMenuItem itemHistorialPagos;
    private javax.swing.JMenuItem itemListarPersonal;
    private javax.swing.JMenuItem itemMonitoreoMesas;
    private javax.swing.JMenuItem itemNuevoInsumo;
    private javax.swing.JMenuItem itemNuevoPedido;
    private javax.swing.JMenuItem itemPagos;
    private javax.swing.JMenuItem itemProdMasVendidos;
    private javax.swing.JMenuItem itemReabastecerInventario;
    private javax.swing.JMenuItem itemRegistrarEmpleadoNuevo;
    private javax.swing.JMenuItem itemVerInventario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenu mesasMenu;
    private javax.swing.JMenu nominaMenu;
    private javax.swing.JMenu pedidoMenu;
    private javax.swing.JMenu personalMenu;
    private javax.swing.JMenu reportesMenu;
    // End of variables declaration//GEN-END:variables
}
