/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ventanasNominas;

import excepciones.BDException;
import gestores.GestorNominas;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Nomina;

/**
 *
 * @author ACER
 */
public class VentanaHistorialPagos extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaHistorialPagos
     */
    public VentanaHistorialPagos() {
        initComponents();
        cargarHistorial();
    }

    private void cargarHistorial() {
        try {
            GestorNominas gestor = new GestorNominas();
            List<Nomina> listaPagos = gestor.listarPagos();

            DefaultTableModel modelo = (DefaultTableModel) tablaHistorial.getModel();
            modelo.setRowCount(0);

            for (Nomina n : listaPagos) {
                modelo.addRow(new Object[]{
                    n.getCodigoNomina(),
                    n.getEmpleado().getDpi() + " - " + n.getEmpleado().getNombre(),
                    n.getEmpleado().getRol(),
                    n.getTipoPago(),
                    "Q " + String.format("%.2f", n.getMontoPago()),
                    n.getFechaEmisionPago().toString(),
                    n.getEstadoPago()
                });
            }

        } catch (BDException ex) {
            JOptionPane.showMessageDialog(this, "Error de base de datos: " + ex.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Historial de Pagos");

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "DPI y Nombre Empleado", "Rol", "Tipo de pago", "Monto", "Fecha", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHistorial;
    // End of variables declaration//GEN-END:variables
}
